### ISSUE TITLE
Add checklist to Publication details page

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-deposition-ui#198]
Add checklist to the Publication details page with these items and links. After all boxes are checked, the "Create Submission" button will be enabled. The checkbox state does not need to be persisted.

Please complete the following checklist before starting you submission. 
 - [x] Elixir registration
 - [x] Install Globus Connect Personal 
 - [x] Link your Elixir account to Globus
 - [x] Format and validate your summary statistics data

**Comment by twhetzel** [comment]
Reviewed and ready to push to prod.
